### ISSUE TITLE
Run `zonal statistics` on Soil Moisture data for all districts for one year

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#11]
As we did for the LST data stream, we will need to perform zonal statistics on Soil Moisture for all outbreak districts for a year. 
This dataset will require an extra step as it is available in daily format and so will require aggregation to monthly, so that it can be combined with both the LST and Precipitation data streams.

Doing this for a year, will be helpful to get an idea of processing time and identify any additional roadblocks (e.g., imputing missing data) that may be required to over come before running the preprocessing script on the full 10 years of data.

**Comment by chuckwondo** [comment]
@kathrynberger, the source for soil moisture data given in the README file is [ESA Climate Data Dashboard](https://climate.esa.int/en/odp/#/project/soil-moisture), which leads to a CEDA archive of _daily_ data: https://data.ceda.ac.uk/neodc/esacci/soil_moisture/data/daily_files/ACTIVE/v07.1

I have been searching for a monthly dataset because it would be much, much easier and faster for at least 2 reasons (as I'm sure you already realize):

1. it would already be at the monthly level, aligning with monthly LST and Precip, so there's no need to aggregate from daily
2. it would not require using 1 URL per _day_, which will result in over 3600 requests (10 years of daily data)

LST requires 1 URL per month, and that's already much slower than Precip. Given that LST and the above Soil moisture data are hosted by CEDA, and the OPeNDAP access to LST at a monthly level has already proven unstable, requesting Soil moisture at a _daily_ level will very likely be even more unstable than LST.

I found this monthly soil moisture dataset, but it appears to be at a spatial resolution of 0.5 degree, not 0.25: https://iridl.ldeo.columbia.edu/SOURCES/.NOAA/.NCEP/.CPC/.GMSM/index.html. Like the Precip data (which has been completely robust to access), this data can be accessed via a single URL, rather than 1 per month or day. However, is a spatial resolution of 0.5 degree too coarse?

**Comment by chuckwondo** [comment]
@kathrynberger, I think I found a better monthly soil moisture dataset: https://www.cen.uni-hamburg.de/en/icdc/data/land/ascat-soilmoisture.html

The spatial resolution is 0.1 degree, so even better than the CEDA data. It's also available via a single URL, rather than a URL per month (where `sm_ext` is the soil moisture variable we're interested in):

```
<xarray.Dataset>
Dimensions:          (lat: 1599, lon: 3207, time: 192)
Coordinates:
  * lat              (lat) float32 -89.94 -89.83 -89.72 ... 89.72 89.83 89.94
  * lon              (lon) float32 -179.9 -179.8 -179.7 ... 179.7 179.8 179.9
  * time             (time) datetime64[ns] 2007-01-16T12:00:00 ... 2022-12-16...
Data variables:
    sm_ext           (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    sm_ext_noise     (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    n_of_sm          (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    n_of_overpasses  (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    snow_cover       (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    frozen_soil      (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    wetland          (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    topography       (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    LDAS_porosity    (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    HWSD_porosity    (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
    status_flag      (time, lat, lon) float32 dask.array<chunksize=(62, 518, 1042), meta=np.ndarray>
Attributes: (12/29)
    Conventions:                CF-1.6
    cdm_data_type:              Grid
    title:                      Monthly average Reprocessed soil moisture map...
    summary:                    The soil moisture time series data of the EUM...
    institution:                Center for Earth System Research and Sustaina...
    creator_url:                https://www.cen.uni-hamburg.de/icdc
    ...                         ...
    time_coverage_duration:     P16Y
    time_coverage_resolution:   P1M
    platform:                   MetOp-A & MetOp-B & MetOp-C
    sensor:                     ASCAT
    source:                     H119/H120 Metop ASCAT soil moisture time seri...
    references:                 [1] W. Wagner, G. Lemoine, and H. Rott: A met...
```

**Comment by kathrynberger** [comment]
@chuckwondo great work on this. Yes, ideally I had been looking for a monthly level soil moisture dataset all along. The one that you shared from Columbia at 0.5 resolution I had avoided as it would be too coarse. The latest dataset that you've identified above from Hamburg looks promising. I see notes to restricted and unrestricted access to this. Is the dataset fully available and what would be the differences? 
I'm fully content to switch to this as a better soil moisture dataset for all of the reasons you have outlined above, I just hadn't come across this one. Most of the soil moisture datasets that are available had been far too coarse to use at the district level for analysis. If you can gain access and it's monthly, at the same or finer resolution - let's switch. I've already checked that it appears to cover the temporal and spatial coverage that we need 👍

**Comment by chuckwondo** [comment]
Subsumed by #12
