### ISSUE TITLE
Combine all three indicator data sources (LST, Precipitation, Soil Moisture) with outbreak data in ML-ready format

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#13]
We will want to concatenate data from each of these three environmental parameter data sources to each district where an outbreak took place. Refer to issue #18  in terms of format. 

In addition to providing mean monthly environmental parameters for each district where an outbreak was recorded, we will also add an additional 3 columns to represent `lag` variables (e.g., an additional column representing mean monthly LST one month prior to outbreak, an additional column for mean monthly LST 2 months prior to outbreak, etc).

**Comment by chuckwondo** [comment]
Minor comment on our use of the term "lag": I suggest we use an antonym of "lag", since a "lag" in this context would be something that comes _after_ an outbreak, not _before_ an outbreak (at least in terms of how I'm interpreting a "lag"), so a term like "prelude" or "advance" might be more appropriate to refer to the zonal means for the months _preceding_ an outbreak. In other words, we're using a 3-month _advance_ of zonal means, not a 3-month _lag_, correct? Am I interpreting things correctly here?

**Comment by chuckwondo** [comment]
Fixed by #25
